version: '3.4'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: online-compiler
    volumes:
      - ./db:/var/lib/postgresql/data
    profiles:
      - db
  

  api:
    build: ./api
    image: compiler_api
    # environment: 
    #   - ROOT=/usr/src/app/
    ports:
      - 9000:9000

  client:
    build: ./client
    image: compiler_client
    environment: 
      - REACT_APP_API_URL=http://api:9000
    ports:
      - 3000:3000
    depends_on: 
      - api

  test:
    image: "cypress/included:3.2.0"
    environment: 
      - CYPRESS_api_url=http://api:9000/
      - CYPRESS_client_url=http://client:3000/
    working_dir: /e2e
    volumes:
      - ./:/e2e
    profiles:
      - test
    depends_on: 
      - api
      - client